# Generated by Django 3.1.4 on 2021-01-02 19:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название компании')),
                ('slug', models.SlugField(max_length=100)),
                ('location', models.CharField(max_length=100, verbose_name='Город')),
                ('logo', models.ImageField(blank=True, upload_to='company_logo/', verbose_name='Логотип')),
                ('description', models.TextField(verbose_name='Текст')),
                ('employee_count', models.PositiveSmallIntegerField(verbose_name='Количество сотрудников')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[(None, 'Выбор кода специальности'), ('frontend', 'frontend'), ('backend', 'backend'), ('gamedev', 'gamedev'), ('devops', 'devops'), ('design', 'design'), ('products', 'products'), ('management', 'management'), ('testing', 'testing')], max_length=100, verbose_name='Код')),
                ('title', models.CharField(choices=[(None, 'Выбор специальности'), ('frontend', 'Фронтенд'), ('backend', 'Бэкенд'), ('gamedev', 'Геймдев'), ('devops', 'Девопс'), ('design', 'Дизайн'), ('products', 'Продукты'), ('management', 'Менеджмент'), ('testing', 'Тестирование')], max_length=100, verbose_name='Название специальности')),
                ('pictures', models.ImageField(upload_to='specialty/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название вакансии')),
                ('slug', models.SlugField(max_length=100)),
                ('skills', models.CharField(max_length=100, verbose_name='Навыки')),
                ('description', models.TextField(verbose_name='Текст')),
                ('salary_min', models.PositiveIntegerField(verbose_name='Зарплата от')),
                ('salary_max', models.PositiveIntegerField(verbose_name='Зарплата до')),
                ('published_at', models.DateField(default=datetime.date.today, verbose_name='Опубликовано')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='main_app.company', verbose_name='Компания')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='main_app.specialty', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='UserWithCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль компании',
                'verbose_name_plural': 'Профили компаний',
            },
        ),
    ]
