# Generated by Django 3.1.4 on 2021-01-08 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_auto_20210103_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=100)),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[(None, 'Готовность к работе'), ('NOT', 'Не ищу работу'), ('OPEN', 'Открыт к предложениям'), ('LOOK', 'Ищу работу')], max_length=100, verbose_name='Готовность к работе')),
                ('grade', models.CharField(choices=[(None, 'Квалификация'), ('IN', 'Стажер (intern)'), ('JR', 'Младший (junior)'), ('ML', 'Средний (middle)'), ('SR', 'Старший (senior)'), ('LD', 'Ведущий (Lead)')], max_length=100, verbose_name='Квалификация')),
                ('salary', models.PositiveIntegerField(verbose_name='Вознаграждение')),
                ('education', models.TextField(verbose_name='Образование')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('portfolio', models.CharField(blank=True, max_length=250, verbose_name='Ссылка на портфолио')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.specialty', verbose_name='Специализация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
