# Generated by Django 3.1.4 on 2021-01-08 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(choices=[('IN', 'Стажер (intern)'), ('JR', 'Младший (junior)'), ('ML', 'Средний (middle)'), ('SR', 'Старший (senior)'), ('LD', 'Ведущий (Lead)')], default='IN', max_length=100, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.ForeignKey(default='frontend', on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.specialty', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('NOT', 'Не ищу работу'), ('OPEN', 'Открыт к предложениям'), ('LOOK', 'Ищу работу')], default='NOT', max_length=100, verbose_name='Готовность к работе'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.PositiveIntegerField(verbose_name='Номер телефона')),
                ('letter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.vacancy')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
